test:
  #  hostport: httpbin.org:80
  #  hostport: localhost:5000
  #  uri: http://${test.hostport}
  uri: https://www.google.com


spring:
  redis:
    timeout: 500
  jmx:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
    io.lettuce.core: DEBUG

management.endpoints.web.exposure.include: '*'